bypass = {
        1: {'version_name': '修订版', 'version_info': '修订版,也称新版,三联版,流传最广,首次阅读推荐阅读此版本',
            'books':{'shen': {'book_name': '神雕侠侣小说', 'book_info': '出版社：三联出版社', 'book_time': '出版时间：1980年', 'version_id': 1} ,
                    'yuan': {'book_name': '鸳鸯刀小说', 'book_info': '出版社：三联出版社', 'book_time': '出版时间：1980年', 'version_id': 1} ,
                    'yi': {'book_name': '倚天屠龙记小说', 'book_info': '出版社：三联出版社', 'book_time': '出版时间：1980年', 'version_id': 1} ,
                    'xiao': {'book_name': '笑傲江湖小说', 'book_info': '出版社：三联出版社', 'book_time': '出版时间：1980年', 'version_id': 1} ,
                    'bi': {'book_name': '碧血剑小说', 'book_info': '出版社：三联出版社', 'book_time': '出版时间：1980年', 'version_id': 1} ,
                    'xia': {'book_name': '侠客行小说', 'book_info': '出版社：三联出版社', 'book_time': '出版时间：1980年', 'version_id': 1} ,
                    'bai': {'book_name': '白马啸西风小说', 'book_info': '出版社：三联出版社', 'book_time': '出版时间：1980年', 'version_id': 1} ,
                    'lian': {'book_name': '连城诀小说', 'book_info': '出版社：三联出版社', 'book_time': '出版时间：1980年', 'version_id': 1} ,
                    'shu': {'book_name': '书剑恩仇录小说', 'book_info': '出版社：三联出版社', 'book_time': '出版时间：1980年', 'version_id': 1} ,
                    'yue': {'book_name': '越女剑小说', 'book_info': '出版社：三联出版社', 'book_time': '出版时间：1980年', 'version_id': 1} ,
                    'xue': {'book_name': '雪山飞狐小说', 'book_info': '出版社：三联出版社', 'book_time': '出版时间：1980年', 'version_id': 1} ,
                    'she': {'book_name': '射雕英雄传小说', 'book_info': '出版社：三联出版社', 'book_time': '出版时间：1980年', 'version_id': 1} ,
                    'fei': {'book_name': '飞狐外传小说', 'book_info': '出版社：三联出版社', 'book_time': '出版时间：1980年', 'version_id': 1} ,
                    'tian': {'book_name': '天龙八部小说', 'book_info': '出版社：三联出版社', 'book_time': '出版时间：1980年', 'version_id': 1} ,
                    'lu': {'book_name': '鹿鼎记小说', 'book_info': '出版社：三联出版社', 'book_time': '出版时间：1980年', 'version_id': 1} ,}
            },

        2: {'version_name': '新修版', 'version_info': '最新修订版，新修版，由广州出版社和花城出版社联合出版',
            'books':{'nxiao': {'book_name': '笑傲江湖小说', 'book_info': '出版社：花城出版社', 'book_time': '出版时间：2006年', 'version_id': 2} ,
                    'nyuan': {'book_name': '鸳鸯刀小说', 'book_info': '出版社：花城出版社', 'book_time': '出版时间：2006年', 'version_id': 2} ,
                    'nxia': {'book_name': '侠客行小说', 'book_info': '出版社：花城出版社', 'book_time': '出版时间：2006年', 'version_id': 2} ,
                    'ntian': {'book_name': '天龙八部小说', 'book_info': '出版社：花城出版社', 'book_time': '出版时间：2005年', 'version_id': 2} ,
                    'nfei': {'book_name': '飞狐外传小说', 'book_info': '出版社：花城出版社', 'book_time': '出版时间：2006年', 'version_id': 2} ,
                    'nbi': {'book_name': '碧血剑小说', 'book_info': '出版社：花城出版社', 'book_time': '出版时间：2006年', 'version_id': 2} ,
                    'nlu': {'book_name': '鹿鼎记小说', 'book_info': '出版社：花城出版社', 'book_time': '出版时间：2006年', 'version_id': 2} ,
                    'nbai': {'book_name': '白马啸西风小说', 'book_info': '出版社：花城出版社', 'book_time': '出版时间：2006年', 'version_id': 2} ,
                    'nshe': {'book_name': '射雕英雄传小说', 'book_info': '出版社：花城出版社', 'book_time': '出版时间：2003年', 'version_id': 2} ,
                    'nxue': {'book_name': '雪山飞狐小说', 'book_info': '出版社：花城出版社', 'book_time': '出版时间：2006年', 'version_id': 2} ,
                    'nyue': {'book_name': '越女剑小说', 'book_info': '出版社：花城出版社', 'book_time': '出版时间：2006年', 'version_id': 2} ,
                    'nyi': {'book_name': '倚天屠龙记小说', 'book_info': '出版社：花城出版社', 'book_time': '出版时间：2006年', 'version_id': 2} ,
                    'nshu': {'book_name': '书剑恩仇录小说', 'book_info': '出版社：花城出版社', 'book_time': '出版时间：2003年', 'version_id': 2} ,
                    'nshen': {'book_name': '神雕侠侣小说', 'book_info': '出版社：花城出版社', 'book_time': '出版时间：2006年', 'version_id': 2} ,
                    'nlian': {'book_name': '连城诀小说', 'book_info': '出版社：花城出版社', 'book_time': '出版时间：2006年', 'version_id': 2} ,}
            },

        3: {'version_name': '旧版', 'version_info': '最初的朗声旧版 报纸连载版',
            'books':{'ofei': {'book_name': '飞狐外传小说', 'book_info': '出版社：武侠与历史', 'book_time': '出版时间：1960年', 'version_id': 3} ,
                    'oxia': {'book_name': '侠客行小说', 'book_info': '出版社：明报月刊', 'book_time': '出版时间：1965年', 'version_id': 3} ,
                    'oshe': {'book_name': '射雕英雄传小说', 'book_info': '出版社：香港商报', 'book_time': '出版时间：1957年', 'version_id': 3} ,
                    'olian': {'book_name': '连城诀小说', 'book_info': '出版社：东南亚周刊', 'book_time': '出版时间：1963年', 'version_id': 3} ,
                    'otian': {'book_name': '天龙八部小说', 'book_info': '出版社：明报', 'book_time': '出版时间：1963年', 'version_id': 3} ,
                    'oshu': {'book_name': '书剑恩仇录小说', 'book_info': '出版社：新晚报', 'book_time': '出版时间：1955年', 'version_id': 3} ,
                    'olu': {'book_name': '鹿鼎记小说', 'book_info': '出版社：报纸连载版', 'book_time': '出版时间：1969年', 'version_id': 3} ,
                    'oyuan': {'book_name': '鸳鸯刀小说', 'book_info': '出版社：明报', 'book_time': '出版时间：1961年', 'version_id': 3} ,
                    'obai': {'book_name': '白马啸西风小说', 'book_info': '出版社：明报', 'book_time': '出版时间：1961年', 'version_id': 3} ,
                    'obi': {'book_name': '碧血剑小说', 'book_info': '出版社：香港商报', 'book_time': '出版时间：1956年', 'version_id': 3} ,
                    'oyi': {'book_name': '倚天屠龙记小说', 'book_info': '出版社：明报', 'book_time': '出版时间：1961年', 'version_id': 3} ,
                    'oshen': {'book_name': '神雕侠侣小说', 'book_info': '出版社：明报', 'book_time': '出版时间：1959年', 'version_id': 3} ,
                    'oxue': {'book_name': '雪山飞狐小说', 'book_info': '出版社：新晚报', 'book_time': '出版时间：1959年', 'version_id': 3} ,
                    'oxiao': {'book_name': '笑傲江湖小说', 'book_info': '出版社：明报周刊', 'book_time': '出版时间：1967年', 'version_id': 3} ,
                    'oyue': {'book_name': '越女剑小说', 'book_info': '出版社：报纸连载版', 'book_time': '出版时间：1970年', 'version_id': 3} ,}
            }
        }
